### ISSUE TITLE
Improve performance 

### ISSUE THREAD

**Issue by Visual-Dawg** [hyprwm/hyprland-website#29]
I am adding issues as a to-do for me and for others who want to contribute.

Improve site performance by:
- Disabling more effects on mobile (especially for `pluginsSlice`)
- Convert to hero background to a svg, which hopefully increases performance. Might be tricky to do though.
- Add a lot more `contain` statements
- Improve the last nitpicks by Lighthouse (I missed to convert a .png for example)
- Probably more

**Comment by xNyfPtx** [comment]
Is it okay to add a JS/CSS toggle on the header to disable animations? The amount of `:hover`s and `filter: ;`s alone make the website lag on my laptop. GSAP could be a possibility too but I'm not sure if it outperforms native CSS.

For how it would disable animations:

```css
 {
  animation-duration: 0.01ms;
  animation-iteration-count: 1;
  transition-duration: 0.01ms;
}
```
